baseurl = "http://mohammedafzel.github.io/mohammedafzel/"
languageCode = "en-US"
publishDir = "docs"
title = "Mohammed Afzel"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Mohammed Afzel"
  description = "Hey there, this is my personal website"
  bio = "I build and maintain front-end and backend systems. Designed & developed membership websites, eCommerce websites, and customer web portals."


  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "mohammedafzel"
  Email         = "er.mohammed.afzel@gmail.com"
  Twitter       = "mohammed_afzel"
  LinkedIn      = "mohammedafzel"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 200
  url = "/resume/web_developer.pdf"
